export { default as App } from './App';
export * from './components/atomos/Icono';
export * from './components/moleculas/Btnsave';
export * from './main';
export * from './pages/Home';
export * from './pages/Login';
export * from './routes/routes';
export * from './store/AuthStore';
export * from './styles/themes';
export * from './styles/variables';
export * from './supabase/supabsae.config';
export * from './template/HomeTemplate';
export * from './template/LoginTemplate';
