export { default as App } from './App';
export * from './components/atomos/icono';
export * from './components/moleculas/Btnsave';
export * from './main';
export * from './pages/Home';
export * from './pages/Login';
export * from './routes/routes';
export * from './styles/themes';
export * from './styles/variables';
export * from './templates/HomeTemplate';
export * from './templates/LoginTemplate';
